### ISSUE TITLE
Cartopy fail 

### ISSUE THREAD

**Issue by OleMartinChristensen** [innosat-mats/instrument_analysis#7]
![Screenshot from 2022-12-03 16-02-09](https://user-images.githubusercontent.com/32387889/205447349-e0c11a05-6ed1-4921-acfb-f57a1791c310.png)

**Comment by bjornlindr** [comment]
Hmm, an environment specific error (python version, pip/conda or w/e) probably?

**Comment by OleMartinChristensen** [comment]
perhaps you can specify cartopy version in setup.cfg? then I can retry

**Comment by OleMartinChristensen** [comment]
cartopy has dependencies that need to be installed on the system, or use "conda install cartopy"
